# Task parameters
# Task parameters
DATA_DIR = '/workspace/aloha_mujoco_project/snn_aloha/dataset'
TASK_CONFIGS = {
    'aloha_pass_strawberry_0': {
        'dataset_dir': DATA_DIR + '/aloha_pass_strawberry_0',
        'num_episodes': 85,
        'episode_len': 600,
        'camera_names': ['camera_0', 'camera_1', 'camera_2', 'camera_3']
    },
    'aloha_pass_strawberry_1': {
        'dataset_dir': DATA_DIR + '/aloha_pass_strawberry_1',
        'num_episodes': 85,
        'episode_len': 600,
        'camera_names': ['camera_0', 'camera_1', 'camera_2', 'camera_3']
    },
    'aloha_clutter': {
        'dataset_dir': DATA_DIR + '/aloha_clutter',
        'num_episodes': 85,
        'episode_len': 1400,
        'camera_names': ['camera_0', 'camera_1', 'camera_2', 'camera_3']
    },
}

# ALOHA fixed constants
FPS = 30
DT = 1 / FPS
JOINT_NAMES = ["waist", "shoulder", "elbow", "forearm_roll", "wrist_angle", "wrist_rotate"]
START_ARM_POSE = [0, -0.96, 1.16, 0, -0.3, 0, 0.02239, -0.02239, 0, -0.96, 1.16, 0, -0.3, 0, 0.02239, -0.02239]


# Left finger position limits (qpos[7]), right_finger = -1 * left_finger 
MASTER_GRIPPER_POSITION_OPEN = 0.02417
MASTER_GRIPPER_POSITION_CLOSE = 0.01244
PUPPET_GRIPPER_POSITION_OPEN = 0.05800
PUPPET_GRIPPER_POSITION_CLOSE = 0.01844

# Dynamixel current limit register value.
PUPPET_GRIPPER_CURRENT_LIMIT = 120

MASTER2PUPPET_JOINT_SCALE = 1.0
MASTER2PUPPET_JOINT_OFFSET = 0.0

# Gripper joint calibration from aloha_ros_record.py, measured on 2026-05-21.
LEFT_MASTER_GRIPPER_JOINT_TELEOP_OPEN = 0.7823
LEFT_MASTER_GRIPPER_JOINT_TELEOP_CLOSE = -0.1028
LEFT_PUPPET_GRIPPER_JOINT_SAFE_OPEN = 0.0721
LEFT_PUPPET_GRIPPER_JOINT_SAFE_CLOSE = -1.3959

RIGHT_MASTER_GRIPPER_JOINT_TELEOP_OPEN = 0.8023
RIGHT_MASTER_GRIPPER_JOINT_TELEOP_CLOSE = -0.0644
RIGHT_PUPPET_GRIPPER_JOINT_SAFE_OPEN = 0.1166
RIGHT_PUPPET_GRIPPER_JOINT_SAFE_CLOSE = -1.3606

# Backward-compatible default names use the average of the two calibrated sides.
MASTER_GRIPPER_JOINT_OPEN = (
    LEFT_MASTER_GRIPPER_JOINT_TELEOP_OPEN + RIGHT_MASTER_GRIPPER_JOINT_TELEOP_OPEN
) / 2.0
MASTER_GRIPPER_JOINT_CLOSE = (
    LEFT_MASTER_GRIPPER_JOINT_TELEOP_CLOSE + RIGHT_MASTER_GRIPPER_JOINT_TELEOP_CLOSE
) / 2.0
PUPPET_GRIPPER_JOINT_OPEN = (
    LEFT_PUPPET_GRIPPER_JOINT_SAFE_OPEN + RIGHT_PUPPET_GRIPPER_JOINT_SAFE_OPEN
) / 2.0
PUPPET_GRIPPER_JOINT_CLOSE = (
    LEFT_PUPPET_GRIPPER_JOINT_SAFE_CLOSE + RIGHT_PUPPET_GRIPPER_JOINT_SAFE_CLOSE
) / 2.0
MASTER_GRIPPER_JOINT_MID = (MASTER_GRIPPER_JOINT_OPEN + MASTER_GRIPPER_JOINT_CLOSE) / 2.0
LEFT_MASTER_GRIPPER_JOINT_MID = (
    LEFT_MASTER_GRIPPER_JOINT_TELEOP_OPEN + LEFT_MASTER_GRIPPER_JOINT_TELEOP_CLOSE
) / 2.0
RIGHT_MASTER_GRIPPER_JOINT_MID = (
    RIGHT_MASTER_GRIPPER_JOINT_TELEOP_OPEN + RIGHT_MASTER_GRIPPER_JOINT_TELEOP_CLOSE
) / 2.0

PUPPET_GRIPPER_JOINT_SAFE_CLOSE = max(
    LEFT_PUPPET_GRIPPER_JOINT_SAFE_CLOSE,
    RIGHT_PUPPET_GRIPPER_JOINT_SAFE_CLOSE,
)
PUPPET_GRIPPER_JOINT_SAFE_OPEN = min(
    LEFT_PUPPET_GRIPPER_JOINT_SAFE_OPEN,
    RIGHT_PUPPET_GRIPPER_JOINT_SAFE_OPEN,
)

############################ Helper functions ############################

MASTER_GRIPPER_POSITION_NORMALIZE_FN = lambda x: (x - MASTER_GRIPPER_POSITION_CLOSE) / (MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE)
PUPPET_GRIPPER_POSITION_NORMALIZE_FN = lambda x: (x - PUPPET_GRIPPER_POSITION_CLOSE) / (PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE)
MASTER_GRIPPER_POSITION_UNNORMALIZE_FN = lambda x: x * (MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE) + MASTER_GRIPPER_POSITION_CLOSE
PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN = lambda x: x * (PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE) + PUPPET_GRIPPER_POSITION_CLOSE
MASTER2PUPPET_POSITION_FN = lambda x: PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN(MASTER_GRIPPER_POSITION_NORMALIZE_FN(x))

def _normalize(x, lo, hi):
    return (x - lo) / (hi - lo)


def _unnormalize(x, lo, hi):
    return x * (hi - lo) + lo


def _clamp(x, lo, hi):
    return min(max(x, lo), hi)


MASTER_GRIPPER_JOINT_NORMALIZE_FN = lambda x: _normalize(x, MASTER_GRIPPER_JOINT_CLOSE, MASTER_GRIPPER_JOINT_OPEN)
PUPPET_GRIPPER_JOINT_NORMALIZE_FN = lambda x: _normalize(x, PUPPET_GRIPPER_JOINT_CLOSE, PUPPET_GRIPPER_JOINT_OPEN)
MASTER_GRIPPER_JOINT_UNNORMALIZE_FN = lambda x: _unnormalize(x, MASTER_GRIPPER_JOINT_CLOSE, MASTER_GRIPPER_JOINT_OPEN)
PUPPET_GRIPPER_JOINT_UNNORMALIZE_FN = lambda x: _unnormalize(x, PUPPET_GRIPPER_JOINT_CLOSE, PUPPET_GRIPPER_JOINT_OPEN)
MASTER2PUPPET_JOINT_FN = lambda x: get_master2puppet_joint_target(x)

def get_master2puppet_joint_target(master_gripper_signal, side=None):
    if side == 'left':
        master_close = LEFT_MASTER_GRIPPER_JOINT_TELEOP_CLOSE
        master_open = LEFT_MASTER_GRIPPER_JOINT_TELEOP_OPEN
        puppet_close = LEFT_PUPPET_GRIPPER_JOINT_SAFE_CLOSE
        puppet_open = LEFT_PUPPET_GRIPPER_JOINT_SAFE_OPEN
    elif side == 'right':
        master_close = RIGHT_MASTER_GRIPPER_JOINT_TELEOP_CLOSE
        master_open = RIGHT_MASTER_GRIPPER_JOINT_TELEOP_OPEN
        puppet_close = RIGHT_PUPPET_GRIPPER_JOINT_SAFE_CLOSE
        puppet_open = RIGHT_PUPPET_GRIPPER_JOINT_SAFE_OPEN
    else:
        master_close = MASTER_GRIPPER_JOINT_CLOSE
        master_open = MASTER_GRIPPER_JOINT_OPEN
        puppet_close = PUPPET_GRIPPER_JOINT_CLOSE
        puppet_open = PUPPET_GRIPPER_JOINT_OPEN

    normalized_master = _normalize(master_gripper_signal, master_close, master_open)
    scaled_normalized = _clamp(
        MASTER2PUPPET_JOINT_SCALE * normalized_master + MASTER2PUPPET_JOINT_OFFSET,
        0.0,
        1.0,
    )
    return _unnormalize(scaled_normalized, puppet_close, puppet_open)

MASTER_GRIPPER_VELOCITY_NORMALIZE_FN = lambda x: x / (MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE)
PUPPET_GRIPPER_VELOCITY_NORMALIZE_FN = lambda x: x / (PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE)

MASTER_POS2JOINT = lambda x: MASTER_GRIPPER_POSITION_NORMALIZE_FN(x) * (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE) + MASTER_GRIPPER_JOINT_CLOSE
MASTER_JOINT2POS = lambda x: MASTER_GRIPPER_POSITION_UNNORMALIZE_FN((x - MASTER_GRIPPER_JOINT_CLOSE) / (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE))
PUPPET_POS2JOINT = lambda x: PUPPET_GRIPPER_POSITION_NORMALIZE_FN(x) * (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE) + PUPPET_GRIPPER_JOINT_CLOSE
PUPPET_JOINT2POS = lambda x: PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN((x - PUPPET_GRIPPER_JOINT_CLOSE) / (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE))
